### ISSUE TITLE
Tweepy

### ISSUE THREAD

**Issue by legendarynacar** [mazlumagar/twitter-analysis#1]
"C:\Users\legendarynacar\PycharmProjects\DONT_OPEN_NEW_FOLDER\PublicApps>python Twitter.py -u legendarynacar
Traceback (most recent call last):
  File "Twitter.py", line 27, in <module>
    t.find_not_following(args.username)
  File "C:\Users\legendarynacar\PycharmProjects\DONT_OPEN_NEW_FOLDER\PublicApps\TwitterAnalysis.py", line 34, in find_not_following
    followers = [user.screen_name for user in tweepy.Cursor(self.api.followers, screen_name=user_name).items()]
  File "C:\Users\legendarynacar\PycharmProjects\DONT_OPEN_NEW_FOLDER\PublicApps\TwitterAnalysis.py", line 34, in <listcomp>
    followers = [user.screen_name for user in tweepy.Cursor(self.api.followers, screen_name=user_name).items()]
  File "C:\Program Files (x86)\Python 3.5\lib\site-packages\tweepy-3.5.0-py3.5.egg\tweepy\cursor.py", line 49, in **next**
  File "C:\Program Files (x86)\Python 3.5\lib\site-packages\tweepy-3.5.0-py3.5.egg\tweepy\cursor.py", line 197, in next
  File "C:\Program Files (x86)\Python 3.5\lib\site-packages\tweepy-3.5.0-py3.5.egg\tweepy\cursor.py", line 75, in next
  File "C:\Program Files (x86)\Python 3.5\lib\site-packages\tweepy-3.5.0-py3.5.egg\tweepy\binder.py", line 245, in _call
  File "C:\Program Files (x86)\Python 3.5\lib\site-packages\tweepy-3.5.0-py3.5.egg\tweepy\binder.py", line 229, in execute
tweepy.error.TweepError: [{'code': 215, 'message': 'Bad Authentication data.'}]
"

Hatası alıyorum. Nasıl çözebilirim?

**Comment by mazlum** [comment]
Aldığın hata authentication hatası. Kullandıgın keyleri kontrol etmen gerek.
